title: Your awesome title(My)
author: SALOway
email: you dont want to know
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 Why you here?

# social links
twitter_username: SALOway # DO NOT include the @ character, or else the build will fail!
github_username:  SALOway # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
